### ISSUE TITLE
Dump-Autoload

### ISSUE THREAD

**Issue by aejnsn** [orchestral/tenanti#15]
![screen shot 2015-04-13 at 1 59 28 am](https://cloud.githubusercontent.com/assets/5347897/7110515/e37dd0f8-e180-11e4-9c52-d850666d11a4.png)

Upon running `php artisan tenanti:make {driver} {migration-name}` I get the above. Seems to stem from line 67 in tenanti/src/Console/MigrateMakeCommand.php.

I changed line 67 from:
`$this->call('dump-autoload');`

to:
`$this->call('clear-compiled');`

This fixed the issue on Laravel 5.0.16. I can PR a fix for this if you like.

**Comment by crynobone** [comment]
Well, you could actually remove `$this->call('dump-autoload');`. `clear-compiled` doesn't do anything useful for us.

Thank for the report.

**Comment by crynobone** [comment]
Wait, I think we need to do something differently here. Let me check something and get this fixed.

**Comment by aejnsn** [comment]
That was fast. I don't know what I was thinking, it's late here in the States.

**Comment by crynobone** [comment]
Should be fixed in https://github.com/orchestral/tenanti/releases/tag/v3.0.3
