### ISSUE TITLE
Add ability to resolve dynamic database connection.

### ISSUE THREAD

**Issue by crynobone** [orchestral/tenanti#19]
At the moment Tenanti works well with single database connection but we need a good way to resolve database.name when it being used on multiple database setup.

**Comment by Zyles** [comment]
Hi. I am in dire need of multi database "SaaS" style setup in Laravel/Lumen and there seems to be no easy way of doing this as most other ways I have seen are hacks and there seem to be no good packages except this one.

Detecting the tenant seems to be done in multiple ways. Some use subdomains and others use URLs. The conclusion is that I think it should be able to be set to a PHP variable like $tenant and you can solve it however you wish.

If you use subdomain approach you can maybe create a middleware to detect the host and set the $tenant, verify it exists in your application and tenanti will take over from there handling the database connection?

If you use URL approach with routes you can have {tenant} in your route. For example it might be like: api.example.com/{tenant}/users which does into your base controller and sets up the database connection.

Is this possible or is this "too late" in the Laravel runtime?

Connection information to the other databases could be stored in the main database or separate config files.

**Comment by abosami2000** [comment]
Hi , can I use multi connection ? some of models using Main connection (no tenats) and other conection is dynamic connection ( tenants ) 

https://github.com/orchestral/tenanti/issues/57
