### ISSUE TITLE
Add some examples for console support

### ISSUE THREAD

**Issue by shanecp** [orchestral/tenanti#20]
Great package!

Might be better to add some examples of console migrations.

Took me sometime to figure-out how to create migrations. (They were missing the table name)

If anyone else is looking, the code to generate migrations properly: (to create a table called 'cars')
`php artisan tenanti:make user cars --create=true --table=cars`

**Comment by crynobone** [comment]
`php artisan tenanti:make` follows exactly how `php artisan make:migration` works. In fact most of the command closely follows the basic migrations.
