### ISSUE TITLE
Hostname based ?

### ISSUE THREAD

**Issue by sherkhanz** [orchestral/tenanti#22]
Hi, I have a quick question, does this package load data from database based on the hostnames? If yes then can it use multiple host names for same tenant_id .
and 3rd thing is that can this package use a single database with same amount of columns and load tenant data based on a specific column declared in each table let say tenant_id?

Thanks

**Comment by crynobone** [comment]
> does this package load data from database based on the hostnames? If yes then can it use multiple host names for same tenant_id .

This package handle database migration for tenant, and that's it.

> 3rd thing is that can this package use a single database with same amount of columns and load tenant data based on a specific column declared in each table let say tenant_id?

No, we don't do that. If for example a blogs app, each tenant would have it's own `blogs` table such as `tenant_1_posts`, `tenant_2_posts` table.

**Comment by sherkhanz** [comment]
Okay thank you so much, you are awesome :+1: :)
