### ISSUE TITLE
Database creation example

### ISSUE THREAD

**Issue by Azuka** [orchestral/tenanti#24]
Do you have an example for the actual database creation for a multi-database setup? Do we actually have to call the create command?

When I call ` php artisan tenanti:migrate account`

I get this error:

`SQLSTATE[HY000] [1049] Unknown database 'app_account_1'`

where my driver and model are both called `account.` Should I be doing something like this?

```php
Tenanti::connection('tenants', function (Account $entity, array $config) {
            $config['database'] = "app_account_{$entity->getKey()}";
            // pseudo code
           if not database exists $config['database'] 
                create database;
            return $config;
        });
```

or is the creation of databases already handled by tenanti?

**Comment by crynobone** [comment]
You can look into https://github.com/crynobone/todoist/compare/single-database...multi-database

**Comment by Azuka** [comment]
Thanks. I'm doing something similar already.

I also overrode the delete because I'm using a soft delete method and didn't want to roll back on delete.
