### ISSUE TITLE
Commands failed

### ISSUE THREAD

**Issue by reefki** [orchestral/tenanti#30]
I am using Laravel 5.3 using multiple database connection with `sqlite` driver. Got error when run `php artisan tenanti:rollback user` the tables are deleted but got following errors.

```
[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined method Orchestra\Tenanti\Console\RollbackCommand::writeMigrationOutput()
```

With `php artisan tenanti:refresh user` the output is very strange, it seems to be drops all tables but then saying `Nothing to migrate`

```
UserTenantCreatePostsTable [users:1]: drop table "posts"
....
Nothing to migrate.
```

When run `php artisan tenanti:reset user` no error thrown but the tables are not deleted.

**Comment by crynobone** [comment]
Done with `php artisan tenanti:rollback user`.

But I can't understand `php artisan tenanti:refresh user` are able to drop table when `php artisan tenanti:reset user` because `tenanti:refresh` is calling `tenanti:reset` and `tenanti:migrate` internally.
