### ISSUE TITLE
Multiple database with shared master users

### ISSUE THREAD

**Issue by deleugpn** [orchestral/tenanti#31]
I'm trying to write a login page where the application connects to a master database and take the database name from the authenticated user. After that, the multiple database tenancy comes to make every model (except the users) to take the tenant connection with a different database.

Sadly, I'm unable to do it and the docs is very confusing regarding multiple databases. Anybody got anything similar that could shed some light into why I can only get a connection in the database set on .env file?

**Comment by crynobone** [comment]
Up to community to contribute on this, I know a few has been doing multiple database setup.

**Comment by nguyenhaiphan** [comment]
@deleugpn I'm managed to successfully switching between master and tenants database. How is your problem?

**Comment by blomdahldaniel** [comment]
@nguyenhaiphan can you share your solution here or in another repo? I would very much like to se how you solved this! :)
