### ISSUE TITLE
[3.3] Migration runDown isn't working

### ISSUE THREAD

**Issue by fernandobandeira** [orchestral/tenanti#36]
When using reset, or refresh, for example, the package isn't running the runDown migration, instead it's always pretending to run the migration and dumps the result on the console.

I've checked and the content that is being passed to the $pretend variable is
```php
[
    'pretend' => false,
]
```

However on Migrator.php it's checking it like:
```php
if ($pretend) {
    return $this->pretendToRun($instance, 'down');
}
```

I'll try to create a PR for this, but i'm not sure if this also happens with lower versions of the package so I'm posting here beforehand so you can check the issue too...

**Comment by crynobone** [comment]
Where is this code located?

```php
if ($pretend) {
    return $this->pretendToRun($instance, 'down');
}
```

**Comment by crynobone** [comment]
Never, see the PR reviews.

**Comment by crynobone** [comment]
Bugfix merged, can you test and verify on your end before I tag a patch release.

**Comment by fernandobandeira** [comment]
Sure, tested on 3.3@dev, fixed the issue for both reset and refresh commands.
