### ISSUE TITLE
3.4.x@dev migrations

### ISSUE THREAD

**Issue by nikosalonen** [orchestral/tenanti#38]
Hello,

I created driver `user` with  `php artisan tenanti:install user` and then test migration with `php artisan tenanti:make user test` which resulted to `Created Migration: 2017_03_08_083742_user_tenant_test`

Now in the migration file am I supposed to use the `Schema` builder to make the tenanti migrations? I can't find example from the documentation. 

I tried to use `Schema`. `up()` function creates the tables but the `down()` does not work when I try `php artisan tenanti:refresh user`. It gives me error ` [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Illuminate\Database\Migrations\Migrator::resetMigrations() must be of the type array, string given, called in /home/vagrant/Code/erp/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.
  php on line 277` for `Schema::dropIfExists('test');`

Laravel version 5.4.15
Tenanti is set to Multi Database Connection

**Comment by crynobone** [comment]
Should be fixed with 514ce4d
