### ISSUE TITLE
Error while trying to execute "php artisan tenanti:install account"

### ISSUE THREAD

**Issue by gabrielbuzziv** [orchestral/tenanti#39]
```
public function boot()
    {
        Tenanti::connection('account', function (Account $account, array $config) {
            $config['database'] = "saas_{$account->slug}";

            return $config;
        });
    }
```

For some reason this resolver is throwing the error below:

```
Argument 2 passed to App\Providers\AppServiceProvider::App\Providers\{closure}() must be of the type array, object given 
```

**Comment by crynobone** [comment]
Which Laravel version?

BTW, the first parameter is required to be set to `$entity`, we're using `Illuminate\Container\Container::call()` method here, and we already bind the relevant model to `$entity`, Defining `Account $account` would mean the container would then build a new `Account` object.

**Comment by gabrielbuzziv** [comment]
Change to `$entity` solved this problem, thanks.
