### ISSUE TITLE
Single database Multiple Schemas

### ISSUE THREAD

**Issue by gabrielbuzziv** [orchestral/tenanti#40]
Is possible o manage the migrations in a single db multi schemas?

**Comment by crynobone** [comment]
I don't understand the question

**Comment by gabrielbuzziv** [comment]
In Postgree, i can have a single database with a lot of schemas.
So i was thinking if is possible to manage this with this package.

You can read about this approach in this article
http://www.summa.com/blog/2013/09/17/approaches-to-multi-tenancy

## SEPARATE SCHEMA PER TENANT

**Comment by crynobone** [comment]
If someone submit a PR to handle this, shouldn't be a problem. I don't have the time to implement this on my own.

**Comment by gabrielbuzziv** [comment]
No problem, i was just asking if have support for this, thanks :P

**Comment by crynobone** [comment]
We have single database with "namespaced" table name, such as `user_1_posts` (formatting is optional). but not per postgres schema (not using Postgres).
