### ISSUE TITLE
--path is not enabled in the make, migrate and rollback command.

### ISSUE THREAD

**Issue by gabrielbuzziv** [orchestral/tenanti#42]
I want to migrate a specific migration and i can't because `--path` is not enabled in the titled commands.

Default Laravel examples
`php artisan make:migration alter_table_web_directories --path=database/migrations/batch_1`
`php artisan migrate alter_table_web_directories --path=database/migrations/batch_1` 
`php artisan migrate:rollback alter_table_web_directories --path=database/migrations/batch_1`

**Comment by crynobone** [comment]
No plan for this.
