### ISSUE TITLE
How to use Laravel Passport with separate table multi tenant architecture?

### ISSUE THREAD

**Issue by mrajabtech** [orchestral/tenanti#47]
Could any one please guide how to integrate laravel passport with tenant databases?

Should I keep the Laravel OAuth tables just in Central database or duplicate OAuth tables for every tenant?

Any help would be appreciated.

**Comment by crynobone** [comment]
You need to do custom work on that.

**Comment by mrajabtech** [comment]
Thanks. Could you please tell me which way do you think is the best? I am planning to duplicate passport tables to each tenant.
