### ISSUE TITLE
Support uuid as tenant database id

### ISSUE THREAD

**Issue by nguyenhaiphan** [orchestral/tenanti#50]
I see that your implementation bind the database with Entity Id, which easily be conflicted after a reset migration. I propose to implement the uuid method instead, which can be randomize uniquely, or an option to connection methods (asConnection) on Orchestra\Tenanti\Migrator\Operation trait so that developer can by pass their own database name, instead of restrictedly following the '_{id}' pattern.

**Comment by crynobone** [comment]
The second parameter is the model instance, so you can handle this on your own.

**Comment by nguyenhaiphan** [comment]
Thank you for your quick response.

Sorry for not clearly describe my situation. I'm using the multi database mode. The tenant table is the company that my clients (user table) belong to. Each user belongTo only one company.

As far as I know, I intend to handle the database connection via middleware, such as:
```
$user = Auth::user();
Tenanti::driver('company')->asDefaultConnection($user->company,'tenants_{id}'));
```
I can't see your mentioned model instance in that implementation.

**Comment by crynobone** [comment]
Dig into the code, `bindWithKey` already handle everything

**Comment by crynobone** [comment]
https://github.com/orchestral/tenanti/blob/master/src/Migrator/Operation.php#L199

**Comment by nguyenhaiphan** [comment]
https://github.com/orchestral/tenanti/blob/2cac5009f03d2685c2f21b62be6546f9dfea55c4/src/Migrator/Operation.php#L195 

When I try to implement my own string, such as ```tenants_<some-uuid>```, the 195th line captured it and transform to something like  ```tenants_<some-uuid>_{id}```. (shared config is set to false for multi dabase mode).

**Comment by nguyenhaiphan** [comment]
So I supposed the database name can have the format like : ```prefix_<uu-id>_{id}``` in the mean time, right :D

**Comment by crynobone** [comment]
I feel lost here, so you telling me that the database connection name need to support other than model key? the same database connection name that Laravel provide by default as `sqlite`, `mysql`?

https://github.com/orchestral/tenanti/blob/master/README.md#database-connection-resolver you can already customize the database name here. Connection name should be irrelevant.

**Comment by nguyenhaiphan** [comment]
Sorry,

Here is my wanting setup:
I have a master database, using 'mysql' connection setting.
In master database I implement the company-user table, in which companies is tenants reference table.
So for each company, I'd like to have a tenants_{uuid} database, instead of tenants_{id}, because when I migrate:refresh the master database and re seed it, the old databases could be lost. Maybe this thing can not be done now. So I decide to go back to your initial solution, which is tenants_{id} format for auto generation database name. (Following your proposal code at https://github.com/crynobone/todoist/blob/multi-database/app/Observers/User.php)

* All tenants database shared the same config from dabase.connection.tenants.*

**Comment by nguyenhaiphan** [comment]
And by the way, how can I achieve the dynamic resolver to each tenants database dynamically base on the company->id at the run time?, I did tried your guide at https://github.com/orchestral/tenanti#setting-default-database-connection but so far not so good.

**Comment by crynobone** [comment]
I don't see any reason why you can't do anything such as https://github.com/crynobone/todoist/blob/multi-database/app/Observers/User.php#L43-L61

```php
/**
 * Create database for entity.
 *
 * @param  \Illuminate\Database\Eloquent\Model  $entity
 *
 * @return mixed
 */
protected function createTenantDatabase(Model $entity)
{
    $connection = $entity->getConnection();
    $driver = $connection->getDriverName();

    switch ($driver) {
        case 'mysql':
            $query = "CREATE DATABASE `todoist_{$entity->uuid}`";
            break;
        case 'pgsql':
            $query = "CREATE DATABASE todoist_{$entity->uuid}";
            break;
        default:
            throw new InvalidArgumentException("Database Driver [{$driver}] not supported");
    }

    return $connection->unprepared($query);
}
```

And resolve the **Database connection** based on https://github.com/crynobone/todoist/blob/multi-database/app/Providers/EventServiceProvider.php#L37-L41

```php
Tenanti::connection('tenants', function (User $entity, array $config) {
    $config['database'] = "todoist_{$entity->uuid}";

    return $config;
});
```

**Comment by nguyenhaiphan** [comment]
Thank you @crynobone ,
I don't now why, but I did put the connection logic to AppServiceProvider as mentioned in the guide, but the trigger never happen. Only when I manage to intercept a customized middleware as mentioned in https://github.com/orchestral/tenanti#setting-default-database-connection, the connection now goes well.
The connection at AppServiceProvider only trigger when I create an item in the observed tenant model.

**Comment by nguyenhaiphan** [comment]
I figured another workaround. 

To change between different tenants databases and master DB (but in same connection : host, user, password), I can use the follow snippet
```php
		\DB::disconnect(config('database.default'));
		config(['database.connections.mysql.database'=>$database_name]);
```php

Thank for great package.
