### ISSUE TITLE
How to queue a specify tenant

### ISSUE THREAD

**Issue by gabrielbuzziv** [orchestral/tenanti#54]
I have a multi database tenanti using orchestral, i want to work with queue, i'm current using database driver, but the problem is that everytime i run the queue fail with message of "No database Selected"

**Comment by crynobone** [comment]
Don't think this currently supported, but anyone can submit a PR to cover this.

**Comment by gabrielbuzziv** [comment]
Did you ever tested queue in a multi database tenanti?
Maybe you can give me a tip or something.

**Comment by crynobone** [comment]
> Did you ever tested queue in a multi database tenanti?

My project is on single database tenanti.

**Comment by gabrielbuzziv** [comment]
Hmm, got it
