### ISSUE TITLE
Update to laravel 5.5 

### ISSUE THREAD

**Issue by paranoid-m** [orchestral/tenanti#55]
Hi 

When update to laravel 5.5?
I have laravel 5.5 and when I run `composer update`  show me this error. 
but It work on laravel 5.4 correctly

> 
  Problem 1
    - orchestra/tenanti v3.3.5 requires illuminate/console ~5.3.26 -> satisfiable by illuminate/console[5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - orchestra/tenanti v3.3.4 requires illuminate/console ~5.3.26 -> satisfiable by illuminate/console[5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - orchestra/tenanti v3.3.3 requires illuminate/console ~5.3.26 -> satisfiable by illuminate/console[5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - orchestra/tenanti v3.3.2 requires illuminate/console ~5.3.26 -> satisfiable by illuminate/console[5.3.x-dev] but these conflict with your requirements or minimum-stability.
    - Conclusion: remove laravel/framework v5.5.9
    - Conclusion: don't install laravel/framework v5.5.9
    - Conclusion: don't install laravel/framework v5.5.8
    - Conclusion: don't install laravel/framework v5.5.7
    - Conclusion: don't install laravel/framework v5.5.6
    - Conclusion: don't install laravel/framework v5.5.5
    - Conclusion: don't install laravel/framework v5.5.4
    - Conclusion: don't install laravel/framework v5.5.3
    - Conclusion: don't install laravel/framework v5.5.2
    - Conclusion: don't install laravel/framework v5.5.1

**Comment by crynobone** [comment]
When I have time to test real app on it, for now use `dev` dependency.

**Comment by paranoid-m** [comment]
Thanks for answer quickly. I tested it and show me this error

>   Problem 1
    - Installation request for orchestra/tenanti dev-master -> satisfiable by orchestra/tenanti[dev-master].
    - orchestra/tenanti dev-master requires illuminate/console ~5.6.0 -> satisfiable by illuminate/console[5.6.x-dev] but these conflict with your requirements or minimum-stability.
