### ISSUE TITLE
Get main databse

### ISSUE THREAD

**Issue by paranoid-m** [orchestral/tenanti#61]
I have main database `maindb` and Tenanti databse name is tenant_{id}
I want to get main database users table
`  Tenanti::driver('user')->asDefaultConnection($userID, 'maindb');`
`   $user=User::all();
            foreach ($user as $key){
                echo $key->name.'<br>';
            }`
but it show me tenant_1 table not maindb

**Comment by crynobone** [comment]
```php
User::on('maindb')...
```
