### ISSUE TITLE
Run laravel dusk on one of tenants

### ISSUE THREAD

**Issue by essivision** [orchestral/tenanti#63]
Hi, 
I wanna to run e2e test by laravel dusk, but it's work on .env file configuration. Do you have any solution to solve it and test multi tenant app

Regards

**Comment by crynobone** [comment]
> Do you have any solution to solve it and test multi tenant app

No, I don't use Laravel Dusk for my own project.

I'm going to close this as this is technically not an issue/bug. But anyone is free to share some experience, if any.
