### ISSUE TITLE
When can I setup this package ?

### ISSUE THREAD

**Issue by mg-freelancer** [orchestral/tenanti#64]
This is not an issue anymore, but I need to know something, I'm writing SaaS application [CRM] which has multi-tenant databases, May I write fully backend and coding for this application and then set up this package at the end because I've developed more features in it before knowing this package. Or Must I rewrite my code from scratch?

**Comment by anil1712** [comment]
Yeah, I also needed almost same. Did you get any solution to it?

**Comment by florinfratica** [comment]
You can setup multi-tenancy using this package on an existing project.
